name: Build addon archive
on:
  release:
    types: [published]
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gitman
        run: pipx install gitman
      - name: install dependencies
        run: gitman install
      - name: Remove git dirs
        run: find libs -type d -name ".git" -execdir rm -rf {} \; -prune
      - run: sed -i "s/{VERSION}/${{ github.event.release.tag_name }}/g" *.toc
      - run: name=$(basename $(pwd)) pushd ..; zip -r $name/release.zip $name; popd 
      - name: Upload artifact to github
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: release.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

