name: Continuous integration
on:
  push:
jobs:
  lint:
    name: Run luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: luacheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
          files: source
  release:
    name: Automated release
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies for semantic-release
        run: npm ci
      - run: $(npm bin)/semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
