name: Continuous integration
on:
  push:
jobs:
  lint:
    name: Run luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: luacheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
          files: source
  release:
    name: Automated release
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
